# Generated by Django 6.0 on 2025-12-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
