# Generated by Django 6.0 on 2025-12-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_notes_public"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notes",
            old_name="public",
            new_name="is_public",
        ),
    ]
